# Generated by Django 5.0 on 2023-12-27 22:11

from django.db import migrations
from store_app.models import Department




def create_departments(apps, schema_editor):
    Department.objects.create(name='Computer Science', wikipedia_link='https://en.wikipedia.org/wiki/Computer_Science')
    Department.objects.create(name='Commerce', wikipedia_link='https://en.wikipedia.org/wiki/Commerce')
    Department.objects.create(name='Mathematics', wikipedia_link="https://en.wikipedia.org/wiki/Mathematics")
    Department.objects.create(name='Science', wikipedia_link='https://en.wikipedia.org/wiki/Science')
    Department.objects.create(name='Arts', wikipedia_link=' href="https://en.wikipedia.org/wiki/Bachelor_of_Arts')


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_course'),
    ]

    operations = [
        migrations.RunPython(create_departments),
    ]
